name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=0.24.1
  - pandas=2.1.3
  - pip:
      - wandb==0.13.9
      - mlflow==2.8.1
      - git+https://github.com/prashant.tank/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components