name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - requests=2.24.0
  - numpy=1.22.4
  - pip:
    - wandb==0.16.0
    - git+https://github.com/prashant.tank/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
